"""Alembic script template."""
"""add hotel scraper config fields

Revision ID: fcd941af6226
Revises: 
Create Date: 2026-07-31 14:44:00.027660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd941af6226'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_keys_is_active', 'api_keys', ['is_active'], unique=False)
    op.create_table('hotels',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraper_rate_limit_rpm', sa.Integer(), nullable=False),
    sa.Column('scraper_burst', sa.Integer(), nullable=False),
    sa.Column('scraper_timeout_ms', sa.Integer(), nullable=False),
    sa.Column('scraper_navigation_timeout_ms', sa.Integer(), nullable=False),
    sa.Column('scraper_selector_timeout_ms', sa.Integer(), nullable=False),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('use_custom_domain', sa.Boolean(), nullable=False),
    sa.Column('scraper_headless', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hotels_is_active', 'hotels', ['is_active'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('hotel_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'id', name='uq_category_hotel_id')
    )
    op.create_index('ix_categories_hotel_id', 'categories', ['hotel_id'], unique=False)
    op.create_table('guests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('hotel_id', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'id', name='uq_guest_hotel_id')
    )
    op.create_index('ix_guests_document', 'guests', ['document_type', 'document_number'], unique=False)
    op.create_index('ix_guests_email', 'guests', ['email'], unique=False)
    op.create_index('ix_guests_hotel_id', 'guests', ['hotel_id'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.String(length=64), nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_logs_hotel_id', 'sync_logs', ['hotel_id'], unique=False)
    op.create_index('ix_sync_logs_started_at', 'sync_logs', ['started_at'], unique=False)
    op.create_index('ix_sync_logs_status', 'sync_logs', ['status'], unique=False)
    op.create_index('ix_sync_logs_sync_type', 'sync_logs', ['sync_type'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('hotel_id', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('floor', sa.String(length=50), nullable=True),
    sa.Column('max_occupancy', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'id', name='uq_room_hotel_id')
    )
    op.create_index('ix_rooms_category_id', 'rooms', ['category_id'], unique=False)
    op.create_index('ix_rooms_hotel_id', 'rooms', ['hotel_id'], unique=False)
    op.create_index('ix_rooms_is_active', 'rooms', ['is_active'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('hotel_id', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('guest_id', sa.String(length=64), nullable=True),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('babies', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('otelms_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otelms_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sync_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'id', name='uq_reservation_hotel_id')
    )
    op.create_index('ix_reservations_check_in', 'reservations', ['check_in'], unique=False)
    op.create_index('ix_reservations_check_out', 'reservations', ['check_out'], unique=False)
    op.create_index('ix_reservations_dates_status', 'reservations', ['check_in', 'check_out', 'status'], unique=False)
    op.create_index('ix_reservations_guest_id', 'reservations', ['guest_id'], unique=False)
    op.create_index('ix_reservations_hotel_id', 'reservations', ['hotel_id'], unique=False)
    op.create_index('ix_reservations_last_synced', 'reservations', ['last_synced_at'], unique=False)
    op.create_index('ix_reservations_room_id', 'reservations', ['room_id'], unique=False)
    op.create_index('ix_reservations_status', 'reservations', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('reservation_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('card_number', sa.String(length=20), nullable=True),
    sa.Column('card_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id', 'id', name='uq_payment_reservation_id')
    )
    op.create_index('ix_payments_date', 'payments', ['date'], unique=False)
    op.create_index('ix_payments_reservation_id', 'payments', ['reservation_id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('reservation_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('legal_entity', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id', 'id', name='uq_service_reservation_id')
    )
    op.create_index('ix_services_date', 'services', ['date'], unique=False)
    op.create_index('ix_services_reservation_id', 'services', ['reservation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_services_reservation_id', table_name='services')
    op.drop_index('ix_services_date', table_name='services')
    op.drop_table('services')
    op.drop_index('ix_payments_reservation_id', table_name='payments')
    op.drop_index('ix_payments_date', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_reservations_status', table_name='reservations')
    op.drop_index('ix_reservations_room_id', table_name='reservations')
    op.drop_index('ix_reservations_last_synced', table_name='reservations')
    op.drop_index('ix_reservations_hotel_id', table_name='reservations')
    op.drop_index('ix_reservations_guest_id', table_name='reservations')
    op.drop_index('ix_reservations_dates_status', table_name='reservations')
    op.drop_index('ix_reservations_check_out', table_name='reservations')
    op.drop_index('ix_reservations_check_in', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index('ix_rooms_is_active', table_name='rooms')
    op.drop_index('ix_rooms_hotel_id', table_name='rooms')
    op.drop_index('ix_rooms_category_id', table_name='rooms')
    op.drop_table('rooms')
    op.drop_index('ix_sync_logs_sync_type', table_name='sync_logs')
    op.drop_index('ix_sync_logs_status', table_name='sync_logs')
    op.drop_index('ix_sync_logs_started_at', table_name='sync_logs')
    op.drop_index('ix_sync_logs_hotel_id', table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index('ix_guests_hotel_id', table_name='guests')
    op.drop_index('ix_guests_email', table_name='guests')
    op.drop_index('ix_guests_document', table_name='guests')
    op.drop_table('guests')
    op.drop_index('ix_categories_hotel_id', table_name='categories')
    op.drop_table('categories')
    op.drop_index('ix_hotels_is_active', table_name='hotels')
    op.drop_table('hotels')
    op.drop_index('ix_api_keys_is_active', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###